### Caso de uso I

### Devolver todos los tests junto con el nombre de usuario
GET http://localhost:3001/api/test



### Caso de uso II

### Devolver las preguntas de un determinado test junto con el nombre de usuario y el nombre del test
GET http://localhost:3001/api/ask/6

### Si el test no existe devuelve un array vacío
GET http://localhost:3001/api/ask/1

### Si el parámetro es un string devuelve un error 400
GET http://localhost:3001/api/ask/kjkds



### Caso de uso III

### Crear un nuevo usuario
POST http://localhost:3001/api/user/register
Content-Type: application/json

{
    "email": "test5@test.com",
    "password": "ajA3dg1-",
    "username": "Pedro"
}

### Hacer login al usario creado
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "email": "test4@test.com",
    "password": "ajA3dg1-"
}

###
GET http://localhost:3001/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZHJvIiwiZW1haWwiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlhdCI6MTczOTA0MTM5NiwiZXhwIjoxNzM5MDQ0OTk2fQ.zGI6p2-AkRRcADg8-sKsUow5aXIQXW1UXSxzHOuPEJA
### Caso de uso IV

### Crear un nuevo test
POST http://localhost:3001/api/test/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZHJvIiwiZW1haWwiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlhdCI6MTczOTAzODgyMSwiZXhwIjoxNzM5MDQyNDIxfQ.VmR7T4FY4cs5yvr7FUjd6EKxCXhb82168LJ4tLDX3tc

{
    "name": "Test de prueba",
    "description": "Este es un test de prueba",
    "category": "Test"
}

### Actualizar un test
PUT http://localhost:3001/api/test/15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZHJvIiwiZW1haWwiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlhdCI6MTczOTAzODgyMSwiZXhwIjoxNzM5MDQyNDIxfQ.VmR7T4FY4cs5yvr7FUjd6EKxCXhb82168LJ4tLDX3tc

{
    "name": "Nuevo nombre",
    "description": "A ver si funciona",
    "category": "Test, prueba"
}

### Eliminar un test: Se debe de eliminar en cascada las preguntas ( se encarga la base de datos)
DELETE http://localhost:3001/api/test/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZHJvIiwiZW1haWwiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlhdCI6MTczOTA0MTM5NiwiZXhwIjoxNzM5MDQ0OTk2fQ.zGI6p2-AkRRcADg8-sKsUow5aXIQXW1UXSxzHOuPEJA

### Crear una nueva pregunta (ask)
POST http://localhost:3001/api/ask/create/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZHJvIiwiZW1haWwiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlhdCI6MTczOTAzNzI1MCwiZXhwIjoxNzM5MDQwODUwfQ.erQa3URSvXUyi1APbEV36Y1P-NbZ2mlbDyRxlFDLgKA

{
    "ask": "¿País mediterráneo de Europa?",
    "answer1": "España",
    "answer2": "Francia",
    "answer3": "Alemania",
    "answer4": "",
    "sol": 1,
    "multi": false,
    "image": "",
    "reference": ""
}

### Actualizar una pregunta
PUT http://localhost:3001/api/ask/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZHJvIiwiZW1haWwiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlhdCI6MTczOTAzODgyMSwiZXhwIjoxNzM5MDQyNDIxfQ.VmR7T4FY4cs5yvr7FUjd6EKxCXhb82168LJ4tLDX3tc

{
    "ask": "¿País mediterráneo del continente europeo?",
    "answer1": "Reino de España",
    "answer2": "País de Francia",
    "answer3": "País de Alemania",
    "answer4": "Inglaterra",
    "sol": 1,
    "multi": false,
    "image": "",
    "reference": ""
}

### Eliminar una pregunta
DELETE http://localhost:3001/api/ask/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZHJvIiwiZW1haWwiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlhdCI6MTczOTA0MTM5NiwiZXhwIjoxNzM5MDQ0OTk2fQ.zGI6p2-AkRRcADg8-sKsUow5aXIQXW1UXSxzHOuPEJA