### Caso de uso I

### Devolver todos los tests junto con el nombre de usuario
GET http://localhost:3001/api/test



### Caso de uso II

### Devolver las preguntas de un determinado test junto con el nombre de usuario y el nombre del test
GET http://localhost:3001/api/ask/6

### Si el test no existe devuelve un array vacío
GET http://localhost:3001/api/ask/1

### Si el parámetro es un string devuelve un error 400
GET http://localhost:3001/api/ask/kjkds



### Caso de uso III

### Crear un nuevo usuario
POST http://localhost:3001/api/user/register
Content-Type: application/json

{
    "email": "test5@test.com",
    "password": "ajA3dg1-",
    "username": "Pedro"
}

### Hacer login al usario creado
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "email": "test4@test.com",
    "password": "ajA3dg1-"
}

###
GET http://localhost:3001/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZHJvIiwiZW1haWwiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlhdCI6MTczOTAxMDEwMSwiZXhwIjoxNzM5MDEzNzAxfQ.N9AYtXXP87647bcKhXud44yBuM2pnCzPaT8GY7n3RMY

### Caso de uso IV

### Crear un nuevo test
POST http://localhost:3001/api/test/create
Content-Type: application/json
Authorization: Bearer iIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZHJvIiwiZW1haWwiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlhdCI6MTczODk1NDMzMSwiZXhwIjoxNzM4OTU3OTMxfQ.qNQ6JQGYO0JzNLOWQlESG2K6P9-97xsRnSUc37cCGZE

{
    "name": "Test de prueba",
    "description": "Este es un test de prueba",
    "category": "Test"
}

### Eliminar un test
DELETE http://localhost:3001/api/test/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZHJvIiwiZW1haWwiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlhdCI6MTczOTAxMDEwMSwiZXhwIjoxNzM5MDEzNzAxfQ.N9AYtXXP87647bcKhXud44yBuM2pnCzPaT8GY7n3RMY

### Crear una nueva pregunta (ask)
POST http://localhost:3001/api/ask/create/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZHJvIiwiZW1haWwiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlhdCI6MTczODk1ODY2OSwiZXhwIjoxNzM4OTYyMjY5fQ.Z72Ws5Vn_Yr0LwsiFdYXWjTQjQQ804dY8OZfkgqVRE8

{
    "ask": "¿País mediterráneo de Europa?",
    "answer1": "España",
    "answer2": "Francia",
    "answer3": "Alemania",
    "answer4": "",
    "sol": 1,
    "multi": false,
    "image": "",
    "reference": ""
}